### ISSUE TITLE
Display more than 100 accounts on "PAY WITH ACCOUNT" list

### ISSUE THREAD

**Issue by kimchi-king** [oxarbitrage/bitshares-explorer#10]
## Account creation:
On the "New BitShares account" page, the dropdown menu for "Pay with Account" is hard coded to only allow 100 names to be listed.

Error:  Object {code: 1, message: "Assert Exception: std::distance(_subscribed_accounts.begin(), _subscribed_accounts.end()) <= 100: ", data: Object}

Can we please increase this to say 1000 or more?

**Comment by oxarbitrage** [comment]
hi there, i think you confused this repo with https://github.com/bitshares/bitshares-ui/issues
this section is for the new bitshares explorer issues only http://bitshares-explorer.io/
