### ISSUE TITLE
Actual source code missing

### ISSUE THREAD

**Issue by knaperek** [oxarbitrage/bitshares-explorer#12]
The project claims to be open source under MIT license; but where's the code? Or am I missing something obvious?

**Comment by oxarbitrage** [comment]
the code for the explorer is noT released yet because the front end use a theme i purchased, i am not sure if that can be open sourced so the actual code will be released after i move all the theme related stuff out. i didn't find the time yet to make it.

**Comment by knaperek** [comment]
The whole thing is a Single Page App though, right? Just Javascript with no server side scripts, right?

The theme is nice; do you think we could make a fundraising to pay the author for releasing it under public domain?

**Comment by oxarbitrage** [comment]
the app haves a server side wrapper in python, thats fully open source and code is available at https://github.com/oxarbitrage/bitshares-python-api-backend

i never digged to much actually over the theme thing. i made the mistake initially to purchase it in themeforest and start developing on top of it.  paid $20 for the regular licence, they have an extended for commercial use license that cost around 900 usd but unsure if the code can be open sourced with any of them.

for reference, the theme url is: https://themeforest.net/item/magic-clean-responsive-admin-with-angularjs/9460276?s_rank=1

licenses info for regular at https://themeforest.net/licenses/terms/regular and  full: https://themeforest.net/licenses/terms/extended

if anyone can provide advice over it will be great,

**Comment by knaperek** [comment]
I'm not a lawyer, but from this it seems we wouldn't be allowed to open-source it even with the extended license:

> 7. This license is a “single application” license and not a “multi-use” license, which means that you **can’t use the Item to create more than one unique End Product**.

> 8. You **can’t** re-distribute the Item as stock, in a tool or template, **or with source files**. You can’t do this with an Item **either on its own or bundled with other items**, and even if you modify the Item. You can’t re-distribute or make available the Item as-is or with superficial modifications.

How much work do you think it would take to refactor it on top of an alternative public domain template? Just wanna compare the options we have; if it's cheaper to pay you for the refactoring work and we won't have any trouble with licensing anymore, then it would be worth consideration.

**Comment by oxarbitrage** [comment]
i will have to do that, not sure how much it will take but will have to do it more sooner than later. full open source explorer is part of my job in bitshares so no additional payment have to be done for this, just need to find the right time to make it happen.

**Comment by oxarbitrage** [comment]
not that hard actually with a better/fresh view, i have it already pretty much splitted. i am going to try to make a release this starting week. labeling as high priority.

**Comment by oxarbitrage** [comment]
sorry in the delay on this, i emailed the theme owner to check if there was a possibility to open source the theme(for a price) but i had got no response so i am resuming the efforts of getting rid of it to open source it. ill post again here soon on the progress.

**Comment by oxarbitrage** [comment]
in hands of the community now to check:
https://bitsharestalk.org/index.php/topic,25570.0.html
will be released soon i hope.

**Comment by wmbutler** [comment]
Doesn't look like anyone has the time to claim this or work it. If you pulled out the theme components and you are getting 0 response from the original developer, are there any real concerns here? What' the worst thing they can do, sue a non-existent entity? I think you've done your due diligence here.

**Comment by oxarbitrage** [comment]
released the code https://github.com/oxarbitrage/open-explorer
