### ISSUE TITLE
will you opensource the exporer code?

### ISSUE THREAD

**Issue by tinyhill666** [oxarbitrage/bitshares-explorer#17]

**Comment by oxarbitrage** [comment]
hi there, yes.

i actually want to do it as soon as possible as i really need the help of others to make faster progress.

this issue explains the reasons why this is not open sourced yet: https://github.com/oxarbitrage/bitshares-explorer/issues/12

and this thread looks for bitshares community members to review the decision by giving access to source code to some of them:

https://bitsharestalk.org/index.php/topic,25570.0.html

I really need the people that already committed to take a look to actually do so:

here is a reminder for them:

- @xeroc
- @ryanRfox
- @wmbutler
- @startailcoon
- @TheTaconator

very appreciated if we can speed this review up a little bit.

**Comment by oxarbitrage** [comment]
released the code. https://github.com/oxarbitrage/open-explorer
