### ISSUE TITLE
Left menu separators

### ISSUE THREAD

**Issue by tbone-bts** [oxarbitrage/bitshares-explorer#3]
Visually, it would be very helpful to use some separators on the left menu considering there are so many items.  See attached.  This gives some visual separation between the governance menu items and the others.

![explorer_leftmenu1](https://user-images.githubusercontent.com/15830348/30180238-33628e5e-93dd-11e7-80a1-cfbed3514bed.JPG)

**Comment by oxarbitrage** [comment]
done this one , it's in the dev version by now. will go to production(version without :9009) soon with some other changes. by now check the separators at:
http://bitshares-explorer.io:9009/#/dashboard

**Comment by tbone-bts** [comment]
cool.  it's definitely an improvement.  the more visually distinct the separator is, the better!

**Comment by oxarbitrage** [comment]
added the separators to the distribution version (http://bitshares-explorer.io), closing the issue.
